# Generated by Django 4.1 on 2024-07-26 02:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'AMap Points',
            },
        ),
        migrations.CreateModel(
            name='AMapPointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='amap_images/')),
                ('map_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='amap.amappoint')),
            ],
        ),
    ]
