# Generated by Django 4.1 on 2024-07-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_mappoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='map_images/')),
                ('map_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='world.mappoint')),
            ],
        ),
    ]
